/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.FileManager;
import backend.FileTypes;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rubén Escalante
 */
public class Config extends javax.swing.JFrame {

    /**
     * Creates new form Config
     */
    public Config() {
        initComponents();
        ArrayList<String> meseros = FileManager.readStringsInFile(FileTypes.MESEROS);
        for (String mesero : meseros) {
            waiterList.add(mesero);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Head = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Body = new javax.swing.JPanel();
        TiempoReporte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        TiempoReporte1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboAgregar = new javax.swing.JComboBox<>();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        waiterTf = new java.awt.TextField();
        waiterList = new java.awt.List();
        saveBtn = new java.awt.Button();
        deleteBtn = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración");
        setLocation(new java.awt.Point(100, 100));
        setMaximumSize(new java.awt.Dimension(450, 460));
        setMinimumSize(new java.awt.Dimension(450, 460));
        setPreferredSize(new java.awt.Dimension(450, 460));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 460));

        Head.setBackground(new java.awt.Color(51, 51, 51));
        Head.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Head.setPreferredSize(new java.awt.Dimension(1269, 50));

        logo.setFont(new java.awt.Font("Quarca Norm Light", 0, 24)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/DayNS32.png"))); // NOI18N
        logo.setText("NullSoft");
        logo.setForeground(new java.awt.Color(187, 187, 187));

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadLayout.createSequentialGroup()
                .addGap(0, 296, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        getContentPane().add(Head, java.awt.BorderLayout.PAGE_START);

        jPanel2.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 200));

        Body.setMinimumSize(new java.awt.Dimension(300, 100));
        Body.setPreferredSize(new java.awt.Dimension(400, 100));

        TiempoReporte.setMinimumSize(new java.awt.Dimension(300, 27));
        TiempoReporte.setPreferredSize(new java.awt.Dimension(300, 27));
        TiempoReporte.setLayout(new javax.swing.BoxLayout(TiempoReporte, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Tipo de reportes: ");
        TiempoReporte.add(jLabel1);

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diario", "Semanal", "Mensual" }));
        jComboBox1.setBorder(null);
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 30));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        TiempoReporte.add(jComboBox1);

        Body.add(TiempoReporte);

        jButton1.setText("Guardar");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Body.add(jButton1);

        TiempoReporte1.setMinimumSize(new java.awt.Dimension(300, 27));
        TiempoReporte1.setPreferredSize(new java.awt.Dimension(300, 27));
        TiempoReporte1.setLayout(new javax.swing.BoxLayout(TiempoReporte1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Modificar: ");
        jLabel2.setToolTipText("Agregar, editar o eliminar las listas de productos. (No para hacer inventario)");
        TiempoReporte1.add(jLabel2);

        comboAgregar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menú", "Bebidas", "Antojos", "Carta", "Extras" }));
        comboAgregar.setBorder(null);
        comboAgregar.setPreferredSize(new java.awt.Dimension(100, 30));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        comboAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAgregarActionPerformed(evt);
            }
        });
        TiempoReporte1.add(comboAgregar);

        Body.add(TiempoReporte1);

        btnModificar.setText("Modificar");
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        Body.add(btnModificar);

        jPanel2.add(Body);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Agregar meseros");
        jPanel2.add(jLabel5);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Meseros");

        waiterTf.setBackground(new java.awt.Color(204, 204, 204));
        waiterTf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        waiterTf.setForeground(new java.awt.Color(102, 102, 102));
        waiterTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waiterTfActionPerformed(evt);
            }
        });

        waiterList.setBackground(new java.awt.Color(204, 204, 204));
        waiterList.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        waiterList.setForeground(new java.awt.Color(102, 102, 102));
        waiterList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waiterListActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(0, 204, 0));
        saveBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        saveBtn.setLabel("Guardar");
        saveBtn.setName(""); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(204, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        deleteBtn.setLabel("Eliminar");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waiterList, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(waiterTf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(waiterList, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(waiterTf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        jPanel2.add(jPanel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void waiterTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waiterTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waiterTfActionPerformed

    private void waiterListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waiterListActionPerformed
        // TODO add your handling code here:
        String selected = waiterList.getSelectedItem();
        waiterTf.setText(selected);
    }//GEN-LAST:event_waiterListActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String selected = waiterTf.getText();
        if (selected.isEmpty() || selected.matches(".*\\d+.*")) {
            JOptionPane.showMessageDialog(new JFrame(), "Ingrese nombre del mesero.");
            return;
        }
        FileManager.addToPlainFile(FileTypes.MESEROS, selected);
        
        waiterTf.setText("");
        waiterList.add(selected);
        MainScreen.INSTANCE.resetUI();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String selectedFile = (String) comboAgregar.getSelectedItem();
        openInventoryManager(selectedFile);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void comboAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAgregarActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String selected = waiterTf.getText();
        FileManager.deleteStringFromFile(FileTypes.MESEROS, selected);
        
        waiterList.remove(selected);
        MainScreen.INSTANCE.resetUI();
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Head;
    private javax.swing.JPanel TiempoReporte;
    private javax.swing.JPanel TiempoReporte1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> comboAgregar;
    private java.awt.Button deleteBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private java.awt.Button saveBtn;
    private java.awt.List waiterList;
    private java.awt.TextField waiterTf;
    // End of variables declaration//GEN-END:variables

    private void openInventoryManager(String selectedFile) {
        
        if(selectedFile.equalsIgnoreCase("menú")){
            FileTypes selected = FileTypes.MENUS;
            new ProductManager(selected).setVisible(true);
        }else{
            
            FileTypes selected = FileTypes.valueOf(selectedFile.toUpperCase());
            new ProductManager(selected).setVisible(true);
        }
    }
}
